### ISSUE TITLE
[documentation] apt upgrade or not ? warning about it ? 

### ISSUE THREAD

**Issue by arthurlutz** [wolfallein/clockworkpi-debian#5]
My first reflex when logging into the image via ssh was to `apt update; apt -uVf dist-upgrade` to see what upgrades where in stock. 

For now, I'm not upgrading the system, but is it recommended ? For example I guess that upgrading retroarch might be a problem since https://github.com/wolfallein/clockworkpi-retroarch/ is not in the package sources... 

While hacking away, installing more packages will upgrade some packages that might break the original retroarch setup. Should there be some pinning in the image ?

**Comment by arthurlutz** [comment]
(for example I'm trying to compile https://github.com/RetroPie/EmulationStation/ and I've had to upgrade some packages 

![Screenshot from 2021-04-12 15-01-17](https://user-images.githubusercontent.com/108437/114398449-17b8ed00-9ba0-11eb-82be-05328c5aebd4.png)

**Comment by wolfallein** [comment]
The image is based on Debian sid (unstable) to get the last updates, mainly because of the recent GPU development.

It shouldn't break with any update because the only binary added to the image is the customized retroarch. You should be able to update and upgrade as you want but since it is based on the Debian sid something can go wrong, but we won't know before you try it :D

BR

**Comment by arthurlutz** [comment]
Updated all packages. retroarch is now the vanilla version. Maybe at least that package could be pinned to the forked version ?

**Comment by arthurlutz** [comment]
After upgrading the patched agetty service is no longer patched so retroarch does not launch at startup. 

Maybe an override systemd file would be more robust ? (Can't seem to get it to work so far)

**Comment by wolfallein** [comment]
All deviation from a standard Debian is on the file `create-debian.sh`

I don't want to hold the retroarch package. The user can hold it after the installation if he wants, I want to keep it as close to a standard Debian as possible.

On line 101 of the file `create-debian.sh` you can see how to do the autologin.

`sed -i "s/ExecStart=-\/sbin\/agetty/ExecStart=-\/sbin\/agetty --autologin cpi/" /lib/systemd/system/getty@.service`

this should do the trick... didn't try

**Comment by arthurlutz** [comment]
the file is patched correctly but upon reboot that doesn't launch retroarch, `systemctl status ` doesn't show getty@tty0...

**Comment by wolfallein** [comment]
Do you get a login screen at least?
