### ISSUE TITLE
mkimage: Can't stat boot.cmd: No such file or directory

### ISSUE THREAD

**Issue by arthurlutz** [wolfallein/clockworkpi-debian#7]
```
mkimage -C none -A arm -T script -d boot.cmd boot.scr
mkimage: Can't stat boot.cmd: No such file or directory
```

Is `boot.cmd` missing from the repo ? Not sure what it is, looking around on other projects I see https://github.com/ninjastorms/ninjastorms/blob/master/boot.cmd which seems to be uboot commands. What boot.scr does is still a bit mysterious to me but reading https://stackoverflow.com/questions/29342821/creating-boot-scr-for-u-boot and https://wiki.debian.org/U-boot?highlight=%28boot.scr%29

**Comment by arthurlutz** [comment]
On that note, I'm confused about `sudo cp -p boot.scr /media/$USER/BOOT/` - it seems that `boot.scr` is in `/` in the image, which is right ?

**Comment by arthurlutz** [comment]
on  a fresh install from the image : 
```
cpi@clockworkpi :/$ cat boot.scr 
'V��d�_
       T���T��setenv bootargs earlyprintk no_console_suspend fsck.repair=yes root=/dev/mmcblk0p1 rootfstype=ext4 rootwait init=/lib/systemd/systemd noinitrd panic=10 cma=256M ${extra}
ext4load mmc 0 0x48000000 /boot/uImage
if gpio input pl11;
then
	ext4load mmc 0 0x49000000 /boot/sun8i-r16-clockworkpi-cpi3.dtb;
else
	ext4load mmc 0 0x49000000 /boot/sun8i-r16-clockworkpi-cpi3-hdmi.dtb;
fi;
bootm 0x48000000 - 0x49000000
cpi@clockworkpi :/$ md5sum boot.scr 
b9e6f19a7d31e114fe20be5a10d4e412  boot.scr
```

**Comment by wolfallein** [comment]
boot.cmd is in the root master repo:

https://github.com/wolfallein/clockworkpi-debian/blob/master/boot.cmd

**Comment by wolfallein** [comment]
> 
> 
> On that note, I'm confused about `sudo cp -p boot.scr /media/$USER/BOOT/` - it seems that `boot.scr` is in `/` in the image, which is right ?

it should be on the boot partition of the image.
